<?php echo '<?xml version="1.0" encoding="UTF-8"?>'; ?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:image="http://www.google.com/schemas/sitemap-image/1.1">
  <url>
    <loc>http://www.limpro.co/</loc>
    <image:image>
      <image:loc>http://www.limpro.co/images/logo_500.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/servicio.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/cotizacion.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/numero_4n.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/numero_8n.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/reloj.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/contrato.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/entrevista.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/garantia.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/calificacion.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/redes.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/monitor.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/conoce_funcionaria.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/limpiar.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/exito.png</image:loc>
    </image:image>
    <image:image>
      <image:loc>http://www.limpro.co/images/trabajo.png</image:loc>
    </image:image>
  </url>
</urlset>